### ISSUE TITLE
Автоматическая подписка нового пользователя на все форумы

### ISSUE THREAD

**Issue by dskarataev** [Xmk/lsplugin-forum#41]
Добрый день, нужна возможность автоматической подписки на форумы при регистрации пользователя. Потому что сейчас такая ситуация, что никто вручную на форумы не подписался, на форуме куча человек, но каждый задает вопросы а никто не отвечает, потому что уведомления о новых темах никому не приходит.

И как можно подписать тех кто уже зарегистрирован?

**Comment by dskarataev** [comment]
напишите какой то ответ, будет сделано или нет и когда?

**Comment by Xmk** [comment]
Добавлено:
- автоматическая подписка на форум, опубликовав в нем топик
- автоматическая подписка на топик, опубликовав в нем пост
