### ISSUE TITLE
Небольшая ошибочка

### ISSUE THREAD

**Issue by yuri25** [Xmk/lsplugin-forum#42]
Наверное просто опечатка...

+$config['topic']['title_min_length'] = 2;
+$config['topic']['title_min_length'] = 100;   наверное должно быть +$config['topic']['title_max_length'] = 100;   
+
+$config['post']['title_min_length'] = 2;
+$config['post']['title_min_length'] = 100;   тоже наверное так  $config['post']['title_max_length'] = 100;

**Comment by yuri25** [comment]
Сделал так
$config['topic']['title_min_length'] = 2;
$config['topic']['title_max_length'] = 500;

$config['post']['title_min_length'] = 2;
$config['post']['title_max_length'] = 500;

Почему то все равно на поле описания ругается...  "Поле описание слишком длинное" Максимально допустимо 100 символов.

**Comment by yuri25** [comment]
Не уверен правильно ли я делаю:) в 36-й строке по аналогии с 35-й написал так:
$this->aValidateRules[]=array('topic_description','string','min'=>Config::Get('plugin.forum.post.title_min_length'),'max'=>Config::Get('plugin.forum.post.title_max_length'), 'allowEmpty'=>true,'label'=>$this->Lang_Get('plugin.forum.new_topic_description'));

Поправьте если я ерунду тут развел.

**Comment by yuri25** [comment]
Что то у меня не туда поехало...:)) При публикации теперь выдало:
Fatal error: Class 'ModuleForum_EntityFile' not found in /...../narkompoisk.ru/engine/classes/Engine.class.php on line 814

**Comment by Xmk** [comment]
Пофиксил опечатку в конфиге
https://github.com/Xmk/lsplugin-forum/commit/df4cf97049135152c4063af64125080d42539b2a
Добавил еще поля в конфиг
https://github.com/Xmk/lsplugin-forum/commit/094dfc6525b5ce368e74c4d76ef6730f31b2d554

Проверьте пожалуйста. Благодарю

**Comment by yuri25** [comment]
Просто у меня версия с каталога с сайта livestreet, а там оказывается вообще нет файла File.entity.class.php  Я добавил этот файл, опубликовал... но там снова какая то ошибка выскочила уже при просмотре темы форума...что то в шаблоне compiled... Сейчас еще раз попробую.

**Comment by Xmk** [comment]
Проблема в строчке #19:
```php
'files'=>array(self::RELATION_TYPE_MANY_TO_MANY,'PluginForum_ModuleForum_EntityFile','file_id','db.table.forum_file_rel','post_id')
```
файла **Post.entity.class.php**

В версии в каталоге эта строчка должна **отсутствовать**

**Comment by yuri25** [comment]
SQL Error: Table 'narkompoisk.prefix_forum_file' doesn't exist at /......../narkompoisk.ru/engine/classes/MapperORM.class.php line 378
Array ( [code] => 1146 [message] => Table 'narkompoisk.prefix_forum_file' doesn't exist [query] => SHOW INDEX FROM prefix_forum_file [context] => /......./narkompoisk.ru/engine/classes/MapperORM.class.php line 378 )  

Наверное это из за того, что изначально версия с каталога установлена. Сайт не мой, товарища, там ему что то Sersar еще правил. Наверное нужно или полностью версию с гита устанавливать либо ограничиться  правкой 35-й строки....

$this->aValidateRules[]=array('topic_title','string','min'=>2,'max'=>100,'allowEmpty'=>false,'label'=>$this->Lang_Get('plugin.forum.new_topic_title'));

**Comment by Xmk** [comment]
Я выше написал в чем проблема

**Comment by yuri25** [comment]
Я разобрался:) (закомментировал эту строку в новом Post.entity.class.php),  спасибо большое, теперь настройки количества символов берутся из конфига и все остальное работает.
